source 'https://cdn.cocoapods.org/'
platform :ios, '16.0'

target 'PicoLLMAppTest' do
  pod 'picoLLM-iOS', :path => '../'
end

target 'PicoLLMAppTestUITests' do
  pod 'picoLLM-iOS', :path => '../'
end
