source 'https://cdn.cocoapods.org/'
platform :ios, '16.0'

target 'PicoLLMAppTest' do
  pod 'picoLLM-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/picollm/v1.1-ios/binding/ios/picoLLM-iOS.podspec'
end

target 'PicoLLMAppTestUITests' do
  pod 'picoLLM-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/picollm/v1.1-ios/binding/ios/picoLLM-iOS.podspec'
end
