-keep class ai.picovoice.picollm.*Exception { <init>(...); }
-keep class ai.picovoice.picollm.PicoLLMCompletion { <init>(...); }
-keep class ai.picovoice.picollm.PicoLLMCompletion$CompletionToken { <init>(...); }
-keep class ai.picovoice.picollm.PicoLLMCompletion$Usage { <init>(...); }
-keep class ai.picovoice.picollm.PicoLLMCompletion$Token { <init>(...); }
-keep class ai.picovoice.picollm.PicoLLMCompletion$Endpoint { *; }
-keep class ai.picovoice.picollm.PicoLLMStreamCallback { *; }
