source 'https://cdn.cocoapods.org/'
platform :ios, '16.0'

target 'PicoLLMChatDemo' do
  pod 'picoLLM-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/picollm/refs/heads/v1.2.3/binding/ios/picoLLM-iOS.podspec'
end