name: Android Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/android-tests.yml'
      - 'binding/android/PicoLLM/**'
      - '!binding/android/PicoLLM/README.md'
      - 'binding/android/PicoLLMTestApp/**'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+']
    paths:
      - '.github/workflows/android-tests.yml'
      - 'binding/android/PicoLLM/**'
      - '!binding/android/PicoLLM/README.md'
      - 'binding/android/PicoLLMTestApp/**'

defaults:
  run:
    working-directory: binding/android/PicoLLMTestApp

jobs:
  build:
    name: Run Android Tests
    runs-on: pv-android

    steps:
    - uses: actions/checkout@v3

    - name: Build binding
      run: ./gradlew assembleRelease
      working-directory: binding/android/PicoLLM

    - name: Download resource files
      run: curl http://${{secrets.PV_CICD_RES_SERVER_AUTHORITY}}/github/picollm/res/phi2-290.bin/latest/phi2-290.bin -o phi2-290.bin

    - name: Copy resource files
      run: ~/Android/Sdk/platform-tools/adb push --sync phi2-290.bin /sdcard/Android/data/ai.picovoice.picollm.testapp/files/external/test_resources/phi2-290.bin

    - name: Inject AccessKey
      run: echo pvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" >> local.properties

    - name: Inject Android keystore variables
      run: echo pvTestingModelName="phi2-290.bin" >> local.properties

    - name: Build androidTest
      run: ./gradlew assembleDebugAndroidTest

    - name: Run tests
      run: ./gradlew connectedAndroidTest --info
