name: iOS Demos

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ios-demos.yml'
      - 'demo/ios/**'
      - '!demo/ios/README.md'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/ios-demos.yml'
      - 'demo/ios/**'
      - '!demo/ios/README.md'

jobs:
  build-completion-demo:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: demo/ios/Completion

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: xcrun xcodebuild build
          -configuration Debug
          -project PicoLLMCompletionDemo.xcodeproj
          -sdk iphoneos
          -scheme PicoLLMCompletionDemo
          -derivedDataPath ddp
          CODE_SIGNING_ALLOWED=NO

  build-chat-demo:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: demo/ios/Chat

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: xcrun xcodebuild build
          -configuration Debug
          -project PicoLLMChatDemo.xcodeproj
          -sdk iphoneos
          -scheme PicoLLMChatDemo
          -derivedDataPath ddp
          CODE_SIGNING_ALLOWED=NO
