name: Node.js

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/nodejs.yml'
      - 'binding/nodejs/**'
      - '!binding/nodejs/README.md'
      - 'lib/node/**'
      - 'resources/.test/**'

  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/nodejs.yml'
      - 'binding/nodejs/**'
      - '!binding/nodejs/README.md'
      - 'lib/node/**'
      - 'resources/.test/**'

defaults:
  run:
    working-directory: binding/nodejs

jobs:
  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      fail-fast: false
      matrix:
        device: [ "cpu" ]
        machine: [ rpi4-32, rpi4-64, rpi5-32, rpi5-64, pv-linux, pv-ios, pv-windows, pv-windows-arm64 ]
        include:
          - device: gpu
            machine: pv-linux
          - device: gpu
            machine: pv-windows
          - device: gpu
            machine: pv-windows-igpu

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: yarn install

    - name: Download resource files
      run: >
        curl http://${{secrets.PV_CICD_RES_SERVER_AUTHORITY}}/github/picollm/res/phi2-290.pllm/06-5842035/phi2-290.pllm -o test/phi2-290.pllm &&
        curl http://${{secrets.PV_CICD_RES_SERVER_AUTHORITY}}/github/picollm/res/qwen3-vl-2b-it-329.pllm/00-5842035/qwen3-vl-2b-it-329.pllm -o test/qwen3-vl-2b-it-329.pllm &&
        curl http://${{secrets.PV_CICD_RES_SERVER_AUTHORITY}}/github/picollm/res/deepseek-ocr-2-310.pllm/00-5842035/deepseek-ocr-2-310.pllm -o test/deepseek-ocr-2-310.pllm &&
        curl http://${{secrets.PV_CICD_RES_SERVER_AUTHORITY}}/github/picollm/res/embeddinggemma-300m-137.pllm/00-5842035/embeddinggemma-300m-137.pllm -o test/embeddinggemma-300m-137.pllm

    - name: Test
      run: yarn test test/index.test.ts --access_key=${{secrets.PV_VALID_ACCESS_KEY}} --device=${{matrix.device}}
