name: SpellCheck

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]

jobs:
  markdown:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install CSpell
        run: npm install -g cspell

      - name: Run CSpell
        run: cspell --config resources/.lint/spell-check/.cspell.json "**/*"
